#undef  DHCP_DISC_START_TIMEOUT_SEC
#define DHCP_DISC_START_TIMEOUT_SEC	1
#undef  DHCP_DISC_END_TIMEOUT_SEC
#define DHCP_DISC_END_TIMEOUT_SEC	6
#undef  DHCP_DISC_PROXY_TIMEOUT_SEC
#define DHCP_DISC_PROXY_TIMEOUT_SEC	0
#undef  DHCP_REQ_END_TIMEOUT_SEC
#define DHCP_REQ_END_TIMEOUT_SEC	4
#undef  DHCP_PROXY_END_TIMEOUT_SEC
#define DHCP_PROXY_END_TIMEOUT_SEC	0
#undef  DHCP_REQ_PROXY_TIMEOUT_SEC
#define DHCP_REQ_PROXY_TIMEOUT_SEC	0
#undef  PXEBS_END_TIMEOUT_SEC
#define PXEBS_END_TIMEOUT_SEC		4
#undef  PXEBS_MAX_TIMEOUT_SEC
#define PXEBS_MAX_TIMEOUT_SEC		3
